from PIL import Image
import os

#nkarneri hetevi fon avelacnel u mejtexic dnel nkare
os.chdir(r"C:\\Users\\karen\\Desktop\\500x500\\")
print(os.listdir(path="."))
image = Image.open(r'C:\\Users\\karen\\Desktop\\12 500x500.jpg')
for i in os.listdir(path="."):
    url = r"C:\\Users\\karen\\Desktop\\500x500\\" + str(i)
    print(url)
    logo = Image.open(url)
    image_copy = image.copy()
    pos1 = int(logo.width/2)
    pos2 = int(logo.height/2)
    pos3 = int(image.width/2)
    pos4 = int(image.height/2)
    print(pos1,pos2,pos3,pos4)
    position = ((pos3-pos1), (pos4-pos2))
    image_copy.paste(logo,position)
    url_save = r"C:\\Users\\karen\\Desktop\\500x500 - resized\\" + str(i)
    image_copy.save(url_save)

os.chdir(r"C:\\Users\\karen\\Desktop\\500x1000\\")
print(os.listdir(path="."))
image = Image.open(r'C:\\Users\\karen\\Desktop\\12 500x1000.jpg')
for i in os.listdir(path="."):
    url = r"C:\\Users\\karen\\Desktop\\500x1000\\" + str(i)
    print(url)
    logo = Image.open(url)
    image_copy = image.copy()
    pos1 = int(logo.width/2)
    pos2 = int(logo.height/2)
    pos3 = int(image.width/2)
    pos4 = int(image.height/2)
    print(pos1,pos2,pos3,pos4)
    position = ((pos3-pos1), (pos4-pos2))
    image_copy.paste(logo,position)
    url_save = r"C:\\Users\\karen\\Desktop\\500x1000 - resized\\" + str(i)
    image_copy.save(url_save)

os.chdir(r"C:\\Users\\karen\\Desktop\\1000x500\\")
print(os.listdir(path="."))
image = Image.open(r'C:\\Users\\karen\\Desktop\\12 1000x500.jpg')
for i in os.listdir(path="."):
    url = r"C:\\Users\\karen\\Desktop\\1000x500\\" + str(i)
    print(url)
    logo = Image.open(url)
    image_copy = image.copy()
    pos1 = int(logo.width/2)
    pos2 = int(logo.height/2)
    pos3 = int(image.width/2)
    pos4 = int(image.height/2)
    print(pos1,pos2,pos3,pos4)
    position = ((pos3-pos1), (pos4-pos2))
    image_copy.paste(logo,position)
    url_save = r"C:\\Users\\karen\\Desktop\\1000x500 - resized\\" + str(i)
    image_copy.save(url_save)